language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t stefanias98/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stefanias98/react-test npm test 

after_success:
  - docker build -t stefanias98/multi-client ./client
  - docker build -t stefanias98/multi-nginx ./nginx
  - docker build -t stefanias98/multi-server ./server
  - docker build -t stefanias98/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push stefanias98/multi-client
  - docker push stefanias98/multi-nginx
  - docker push stefanias98/multi-server
  - docker push stefanias98/multi-worker